#!/usr/bin/env python3
"""Regenerates shared/utils/games.generated.ts from the upstream Django game registry.

Usage: python3 scripts/sync-games.py [path/to/game_type.py]
The integer IDs are the stable identity of a game variant (stored in the DB), so the
registry is generated from the upstream file instead of being maintained by hand.
"""
import importlib.util
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "scripts/upstream/game_type.py"
OUT = ROOT / "shared/utils/games.generated.ts"

spec = importlib.util.spec_from_file_location("game_type", SRC)
mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)

GameType = mod.GameType
variants = []
for gt in GameType:
    variants.append({
        "id": gt.value,
        "key": gt.name,
        "group": gt.group.value,
        "name": gt.long_name,
        "shortName": gt.short_name,
        "variantName": gt.variant_name,
        "hidden": gt in mod.HIDDEN_VARIANTS,
        "custom": gt.is_custom,
        "usesSeed": gt.uses_seed,
    })

groups = []
for group_gt, entry in mod.GAME_GROUPS.items():
    groups.append({
        "id": group_gt.value,
        "name": entry["name"],
        "variants": [gt.value for gt, _, _ in entry["variants"]],
    })

def ts(value):
    return json.dumps(value, ensure_ascii=False, indent=2)

OUT.write_text(
    "// Generated by scripts/sync-games.py from the upstream bingosync game registry. Do not edit.\n"
    "// Regenerate with: python3 scripts/sync-games.py\n\n"
    "export interface GameVariant {\n"
    "  id: number\n  key: string\n  group: number\n  name: string\n  shortName: string\n"
    "  variantName: string\n  hidden: boolean\n  custom: boolean\n  usesSeed: boolean\n}\n\n"
    "export interface GameGroup {\n  id: number\n  name: string\n  variants: number[]\n}\n\n"
    f"export const GAME_VARIANTS: GameVariant[] = {ts(variants)}\n\n"
    f"export const GAME_GROUPS: GameGroup[] = {ts(groups)}\n"
)
print(f"wrote {OUT.relative_to(ROOT)}: {len(variants)} variants, {len(groups)} groups")
